source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'Accent' do
  use_frameworks!

  # Pods for Accent
  pod 'TextFieldEffects', '~> 1.3.0'

  pod 'Alamofire', '~> 1.2'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
